config/routes.rb
Blog::Application.routes.draw do
  devise_for :admins, :skip => :registrations

  resources :posts

	resources :comments

  root :to => "posts#index"

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
	validates_presence_of :name, :email, :body
	validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
	def gravatar_url options = {}
    options = {:alt => 'avatar', :class => 'avatar', :size => 50}.merge! options
		if self.email.nil?
			id = ''
		else	    
			id = Digest::MD5::hexdigest self.email.strip.downcase
		end    
		url = 'http://www.gravatar.com/avatar/' + id + '.jpg?s=' + options[:size].to_s
    options.delete :size
		url
	end

end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments
	has_many :references
	has_many :tags, :through => :references
  attr_writer :tag_names
	after_save :assign_tags
  
  def tag_names
    @tag_names || tags.map(&:name).join(', ')
  end
  
  private
  
  def assign_tags
    if @tag_names
      self.tags = @tag_names.split(/\s+/).map do |name|
        Tag.find_or_create_by_name(name)
    	end
    end
  end
end

app/models/reference.rb
class Reference < ActiveRecord::Base
	belongs_to :tag
	belongs_to :post
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :references
	has_many :posts, :through => :references
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_filter :find_recent_entries
	protect_from_forgery
	
	def find_recent_entries
		@recent_posts = Post.limit(3).order("created_at DESC")
	end
	
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(params[:comment])

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.post, notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
				format.html { redirect_to @comment.post, notice: 'Failed to create comment.' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end
	def destroy
		@comment = Comment.find(params[:id])
		@comment.destroy
	
		respond_to do |format|
			format.html { redirect_to @comment.post, notice: 'Comment was successfully deleted.' }
		end
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_admin!, :except => [:index, :show]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.limit(5).order("created_at DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sarah Riggs, Information Scientist</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>


  <div id="top">
  	<p class="right"><%= link_to 'New Post', new_post_path if admin_signed_in? %></p>
  </div>
	
	<div id="header">
		<div id="headerMiddle">
			<div id="title">
				<a href="/"><img src="/images/sarahriggs.png" alt="sarah riggs"></a>
			</div>
			<div id="navigation">
				<ul>
					<li><a href="#"><img src="/images/blog.png" alt="blog"></a></li>
					<li><img src="/images/portfolio.png" alt="portfolio"></li>
				</ul> 	  	
			</div>
	</div>

  <div id="center">
		<div id="centerMiddle">
			<div id="centerLeft">
				<% flash.each do |key, msg| %>
					<%= content_tag :div, msg, :id => key %>
					<% end %>
				<%= yield %>
			</div>
			<div id="centerRight">
				<div class="social">
					<ul>
						<li><a href="http://www.twitter.com/#/diceratops"><img src="/images/twitter.png" alt="twitter"></a></li>
						<li><a href="http://www.github.com/diceratops"><img src="/images/gh.png" alt="github"></a></li>
						<li><a href="http://www.linkedin.com/in/sarahriggs"><img src="/images/in.png" alt="linkedin"></a></li>
						<li><a href="http://profiles.google.com/diceratops"><img src="/images/google.png" alt="google"></a></li>
					</ul>
				</div>
			</div>
 	 	</div>
	</div>



</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>

<div class="field">
  <%= f.label :tag_names %><br />
  <%= f.text_field :tag_names %>
</div>



  <div class="actions">
	

  <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<p><%= link_to 'Show', @post %> | <%= link_to 'Back', posts_path %></p>

app/views/posts/index.html.erb
<div class="posts">


<% @posts.each do |post| %>
  <div class="post">
    <h3><%= link_to post.title, post %></h3>
		<p class="comment_count"><%= post.comments.count %></p>
    	<div class="post_body"><%= raw RedCloth.new(post.body.truncate(300)).to_html %> <%= link_to ' Read More', post if post.body.length > 300 %>

    	</div>
		<div class="date">Posted on <%= post.created_at %></div>
  </div>
<% end %>

</div>

<%= paginate @posts %>



<br />

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="posts">

  <h2><%= @post.title %></h2>
		<div class="post_body"><%= raw RedCloth.new(@post.body).to_html %></div>
				<p class="date">Posted on <%= @post.created_at %></p>

</div>

<p>
  <h2>Tags:</h2>
  <%= @post.tag_names %>
</p>

<div id="appbar">
  <%= link_to 'Edit Post | ', edit_post_path(@post) if admin_signed_in? %>
	<%= link_to 'Delete Post', @post, confirm: 'Are you sure?', method: :delete if admin_signed_in? %>
</div>

<h2>Comments</h2>
<div class="comments">
	<% @post.comments.each do |comment| %>
		<div class="comment">
			<div class="nameImage"><%= image_tag comment.gravatar_url %></div>
			<p class="name"><%= comment.name %> says . . . </p>
			<p class="body"><%= comment.body %></p>
			<p class="comment_date"><%= comment.created_at %></p>
			<p class="destroy_comment"><%= link_to 'Delete Comment', comment, confirm: 'Are you sure?', method: :delete if admin_signed_in? %></p>
		</div>
	<% end %>
</div>

<div class="form">
	<%= form_for(@post.comments.new) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	
	<%= f.hidden_field :post_id %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

<p class="navback"><%= link_to 'Back to the Blog', posts_path %></p>